module statistics {
       exception StatisticsException {
       };

       interface OrbStatistics {
             const string NAME = "OrbStatistics";
             void publish(in string stat);
       };

       
};